# This workflow will install Python dependencies, pytest and run unit tests

name: Unit Tests on API
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install -r app/requirements.txt

      - name: Run tests
        run: |
          pytest
